version: '2'
services:
  test1:
    build:
      context: https://github.com/Runnable/compose-test-repo-3.1.git
  test2:
    build:
      context: https://github.com/Runnable/compose-test-repo-4.2.git


